version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: outfox_postgres
    environment:
      POSTGRES_DB: health
      POSTGRES_USER: health
      POSTGRES_PASSWORD: health
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: outfox_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: health
      POSTGRES_USER: health
      POSTGRES_PASSWORD: health
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    command: ["bash", "-lc", "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app"]
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:delegated
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge


